### ISSUE TITLE
[rootless] nil pointer dereference panic

### ISSUE THREAD

**Issue by AkihiroSuda** [cri-o/cri-o#2205]
**Description**

```
[crio] panic: runtime error: invalid memory address or nil pointer dereference
[crio] [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x152f39a]
[crio]
[crio] goroutine 60 [running]:
[crio] github.com/kubernetes-sigs/cri-o/oci.(*runtimeOCI).createContainerPlatform(0xc000c56400, 0xc000848840, 0xc00018ec40, 0x3c, 0x1f5)
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/oci/oci_linux.go:45 +0x22a
[crio] github.com/kubernetes-sigs/cri-o/oci.(*runtimeOCI).CreateContainer(0xc000c56400, 0xc000848840, 0xc00018ec40, 0x3c, 0xc0004b7708, 0x0)
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/oci/runtime_oci.go:140 +0xfe3
[crio] github.com/kubernetes-sigs/cri-o/oci.(*Runtime).CreateContainer(0xc0000b3360, 0xc000848840, 0xc00018ec40, 0x3c, 0x46be3d, 0xfaa8)
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/oci/oci.go:268 +0xe0
[crio] github.com/kubernetes-sigs/cri-o/server.(*Server).createContainerPlatform(0xc000405200, 0xc000848840, 0x0, 0xc00018ec40, 0x3c, 0x0, 0x0)
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/server/container_create_linux.go:169 +0x80
[crio] github.com/kubernetes-sigs/cri-o/server.(*Server).runPodSandbox(0xc000405200, 0x1d42f20, 0xc000b022d0, 0xc00097b960, 0x0, 0x0, 0x0)
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/server/sandbox_run_linux.go:628 +0x4c89
[crio] github.com/kubernetes-sigs/cri-o/server.(*Server).RunPodSandbox(0xc000405200, 0x1d42f20, 0xc000b022d0, 0xc00097b960, 0xc000405200, 0x3f00000000, 0xc0008b0c28)
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/server/sandbox_run.go:122 +0x49
[crio] github.com/kubernetes-sigs/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2._RuntimeService_RunPodSandbox_Handler(0x1a46a00, 0xc000405200, 0x1d42f20, 0xc000b022d0, 0xc00099fe50, 0x0, 0x
0, 0x0, 0x0, 0x0)
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/runtime/v1alpha2/api.pb.go:4164 +0x241
[crio] github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000230500, 0x1d5c2e0, 0xc0008494a0, 0xc0009bd600, 0xc00096e5d0, 0x2ef04f8, 0x0, 0x0, 0x0)
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc/server.go:843 +0x94c
[crio] github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000230500, 0x1d5c2e0, 0xc0008494a0, 0xc0009bd600, 0x0)
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc/server.go:1040 +0x12b5
[crio] github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00089b2c0, 0xc000230500, 0x1d5c2e0, 0xc0008494a0, 0xc0009bd600)
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc/server.go:589 +0x9f
[crio] created by github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
[crio]  /go/src/github.com/kubernetes-sigs/cri-o/vendor/google.golang.org/grpc/server.go:587 +0xa1
```

**Steps to reproduce the issue:**
1. Run Usernetes with cri-o 7a329fc0a6198e611ad862a67aca3380406dfc83
https://github.com/rootless-containers/usernetes/pull/91

**Describe the results you received:**

crashed as above

**Describe the results you expected:**

works

@giuseppe

**Comment by giuseppe** [comment]
PR here: https://github.com/cri-o/cri-o/pull/2215
