### ISSUE TITLE
CleanupConmonCgroup  panic

### ISSUE THREAD

**Issue by mariusgrigoriu** [cri-o/cri-o#2620]
**Description**
We tried a build from commit `8f9064819cbaba8f09a4a512e08a094bfd973edd` on the 1.14 release branch and got a bunch of panics.

```
Jul 15 22:07:53 ip-172-16-194-61 crio-wrapper[10172]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 15 22:07:53 ip-172-16-194-61 crio-wrapper[10172]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x15bae24]
Jul 15 22:07:53 ip-172-16-194-61 crio-wrapper[10172]: goroutine 45280 [running]:
Jul 15 22:07:53 ip-172-16-194-61 crio-wrapper[10172]: panic(0x18c8500, 0x2fb93e0)
Jul 15 22:07:53 ip-172-16-194-61 crio-wrapper[10172]:         /usr/local/go/src/runtime/panic.go:565 +0x2c5 fp=0xc0054f3968 sp=0xc0054f38d8 pc=0x4366a5
Jul 15 22:07:53 ip-172-16-194-61 crio-wrapper[10172]: runtime.panicmem(...)
Jul 15 22:07:53 ip-172-16-194-61 crio-wrapper[10172]:         /usr/local/go/src/runtime/panic.go:82
Jul 15 22:07:53 ip-172-16-194-61 crio-wrapper[10172]: runtime.sigpanic()
Jul 15 22:07:53 ip-172-16-194-61 crio-wrapper[10172]:         /usr/local/go/src/runtime/signal_unix.go:390 +0x411 fp=0xc0054f3998 sp=0xc0054f3968 pc=0x44c431
Jul 15 22:07:53 ip-172-16-194-61 crio-wrapper[10172]: github.com/cri-o/cri-o/oci.(*Container).CleanupConmonCgroup(0xc0046b2180)
```

**Steps to reproduce the issue:**
We were able to find similar panics on nodes running close to 100 crash looping pods, hoping to catch the conmon cgroup leak.

**Describe the results you received:**

Full stack trace here:
[panic.log](https://github.com/cri-o/cri-o/files/3398961/panic.log)

**Output of `crio --version`:**
 `8f9064819cbaba8f09a4a512e08a094bfd973edd` on the 1.14 release branch

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CoreOS 2079.6.0
Kubernetes 1.14.3

**Comment by mrunalp** [comment]
@vrothberg ptal

**Comment by vrothberg** [comment]
@mariusgrigoriu was faster, thanks! I am about to backport the commit to 1.14 and 1.15.
