### ISSUE TITLE
Bug: `cri-o` not logging golang's panic as partial `LogTag` 

### ISSUE THREAD

**Issue by kavirajk** [cri-o/cri-o#5903]
### What happened?

`cri-o` persist container logs in the node's disk usually under `/var/log/containers/<pod-name>.log`. And each entry of the log line takes the form.
```
<DATE> <stdout|stderr> <logTag> <LOGLINE>
```

e.g:
```
2022-05-21T22:00:46.835887817+00:00 stderr F I0521 22:00:46.835880       1 secure_serving.go:200] Serving securely on 127.0.0.1:10259
```

Here `logTag` can either be `F` (Full line) or `P` (Partial line).

When any application panics or print stack trace, I expect to see those lines a partial lines (except the last one with `F` tag meaning that's the end of the partial lines)

But when my Go application panics say like below
```
panic: i'm pannicing

goroutine 1 [running]:
main.main()
	/home/kavirajk/src/go-play/main.go:18 +0x27
```

it treats every line as complete `Full line` (F logTag) and dump it as following.
```
docker@minikube:/var/log/containers$ sudo tail goplay-56d78bfdb7-p2kwm_kaviraj_go-play-6d5832a57ba9d6c00f0f37f2cee3839237991e925d7f3283f03de396ebe830d8.log 
2022-05-21T21:41:37.822853908+00:00 stderr F panic: i'm pannicing
2022-05-21T21:41:37.822853908+00:00 stderr F 
2022-05-21T21:41:37.822853908+00:00 stderr F goroutine 1 [running]:
2022-05-21T21:41:37.822853908+00:00 stderr F main.main()
2022-05-21T21:41:37.822853908+00:00 stderr F 	/home/kavirajk/src/go-play/main.go:18 +0x27
```

### What did you expect to happen?

I would expect to see logs for panic like this.
```
2022-05-21T21:41:37.822853908+00:00 stderr P panic: i'm pannicing
2022-05-21T21:41:37.822853908+00:00 stderr P 
2022-05-21T21:41:37.822853908+00:00 stderr P goroutine 1 [running]:
2022-05-21T21:41:37.822853908+00:00 stderr P main.main()
2022-05-21T21:41:37.822853908+00:00 stderr F 	/home/kavirajk/src/go-play/main.go:18 +0x27
```

## 1. Start minikube with `--container-runtime=cri-o`
```bash
cri-o$ minikube start --container-runtime=cri-o
minikube v1.24.0 on Arch 21.2.6
Using the docker driver based on existing profile
Starting control plane node minikube in cluster minikube
Pulling base image ...
Restarting existing docker container for "minikube" ...
Preparing Kubernetes v1.22.3 on CRI-O 1.22.0 ...
Configuring CNI (Container Networking Interface) ...
Verifying Kubernetes components...
Using image gcr.io/k8s-minikube/storage-provisioner:v5
Enabled addons: storage-provisioner, default-storageclass
Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

## 2. Create deployment with golang app that just panic
```bash
kubectl create deployment --image=kavirajk/go-play:1.2 goplay
```

## 3. Check container logs from the node
```bash
cri-o$ minikube ssh
Last login: Sat May 21 22:02:07 2022 from 192.168.49.1
docker@minikube:~$ cd /var/log/containers/
docker@minikube:/var/log/containers$ sudo tail goplay-56d78bfdb7-p2kwm_kaviraj_go-play-6d5832a57ba9d6c00f0f37f2cee3839237991e925d7f3283f03de396ebe830d8.log 
2022-05-21T21:41:37.822853908+00:00 stderr F panic: i'm pannicing
2022-05-21T21:41:37.822853908+00:00 stderr F 
2022-05-21T21:41:37.822853908+00:00 stderr F goroutine 1 [running]:
2022-05-21T21:41:37.822853908+00:00 stderr F main.main()
2022-05-21T21:41:37.822853908+00:00 stderr F 	/home/kavirajk/src/go-play/main.go:18 +0x27
```

### Anything else we need to know?

If my assumptions were wrong that stack trace (or panics) should be treated as Partial Log lines by `cri-o` runtime, can someone educate me what is the exact use case for Partial log lines?

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.22.0
Version:          1.22.0
GitCommit:        6becad23eadd7dfdd25fd8df386bf3b706cf7758
GitTreeState:     clean
BuildDate:        2021-09-17T19:31:48Z
GoVersion:        go1.16.8
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        apparmor, exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false

```

```console
$ kubectl --version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"archive", BuildDate:"2022-04-29T06:39:16Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

$ uname -a
Linux kaviraj-meerkat 5.15.38-1-MANJARO #1 SMP PREEMPT Mon May 9 07:52:21 UTC 2022 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Physical desktop machine.
</details>

**Comment by kavirajk** [comment]
Yea. it was my misunderstanding. Thanks for the clarification.
