### ISSUE TITLE
NRI: CRI-O failed to start when nri enabled

### ISSUE THREAD

**Issue by Tal-or** [cri-o/cri-o#6642]
### What happened?

Enabling nri via `crio.conf`:
```
[crio.nri]
enabled_nri = true
```
Causes CRI-O to crash.

From the logs I can see:
```
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]: time="2023-02-13 07:51:04.003679656Z" level=warning msg="Failed to get pid for pod infra container: container PID
 not initialized" file="server/nri-api.go:447"
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x2aa5707]
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]: goroutine 545 [running]:
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]: panic({0x2d61760, 0x48617d0})
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]:         runtime/panic.go:987 +0x3ba fp=0xc000bc9658 sp=0xc000bc9598 pc=0x104ba5a
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]: runtime.panicmem(...)
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]:         runtime/panic.go:260
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]: runtime.sigpanic()
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]:         runtime/signal_unix.go:835 +0x2f6 fp=0xc000bc96a8 sp=0xc000bc9658 pc=0x10630b6
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]: github.com/cri-o/cri-o/server.toOCIResources(0x0)
Feb 13 07:51:04 dhcp-8-34-235.telco5gran.eng.rdu2.redhat.com crio[2495563]:         github.com/cri-o/cri-o/server/container_update_resources.go:55 +0x87 fp=0xc000bc9748 sp=0xc000bc96a8 pc=0
x2aa5707
```
I've investigated it for a while and the issue lays here:
https://github.com/cri-o/cri-o/blob/main/server/container_update_resources.go#L30 
If nri plugins return `nil` the code crashes.

IMHO there're two different problems here:
1. Each plugin that is running must implement the ```UpdateContainerInterface``` interface and return the resources in order to keep CRI-O from crashing
2. Assuming point no 1 is a reasonable requirement, this means that in order to enable plugin, we should:
  a. Run CRIO (with `enabled_nri = false` otherwise it crashes)
  b. Deploy nri plugin pod
  c. change `enabled_nri = true` 
  d. restart CRIO
IOW we must restart CRIO in order to make the plugin to run - This kind of chicken-egg problem can be avoided by handling the response properly on CRIO side.

### What did you expect to happen?

CRI-O should handle the case when `nil` returns from the plugin and use initial resources request.

### How can we reproduce it (as minimally and precisely as possible)?

1. Enabling nri via `crio.conf`:
```
[crio.nri]
enabled_nri = true
```
2. create empty conf file:
`touch /etc/nri/nri.conf` (also create `nri` dir if needed)
2. restart crio

### Anything else we need to know?

The line number in the log output might not be identical because I added some log line of my own for debugging.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
INFO[2023-02-13 08:02:21.591374747Z] Starting CRI-O, version: 1.26.0, git: 6396f4a48e29f035757061d6f798c57909fa15ef(clean) 
Version:        1.26.0
GitCommit:      6396f4a48e29f035757061d6f798c57909fa15ef
GitCommitDate:  2023-02-02T21:17:47Z
GitTreeState:   clean
BuildDate:      2023-02-05T13:54:03Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  containers_image_ostree_stub
  exclude_graphdriver_btrfs
  btrfs_noversion
  containers_image_openpgp
  seccomp
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies: 
```

```console
$ kubectl --version
Client Version: v1.24.1
Kustomize Version: v4.5.7
Server Version: v1.26.0+083e3f3
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="413.86.202302010248-0"
VERSION_ID="4.13"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 413.86.202302010248-0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.13/"
BUG_REPORT_URL="https://access.redhat.com/labs/rhir/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.13"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.13"
OPENSHIFT_VERSION="4.13"
RHEL_VERSION="8.6"
OSTREE_VERSION="413.86.202302010248-0"
$ uname -a
Linux rhel 4.18.0-372.41.1.rt7.198.el8_6.x86_64 #1 SMP PREEMPT_RT Fri Jan 6 15:08:19 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
OCP cluster with physical + virtual workers 
</details>

**Comment by saschagrunert** [comment]
Hey @Tal-or, thank you for the report! This indeed looks like a valid bug, do you plan to open a PR providing a fix?

**Comment by Tal-or** [comment]
If I may, then yes, I already have something

**Comment by Tal-or** [comment]
PR fixing the issue: https://github.com/cri-o/cri-o/pull/6645
