### ISSUE TITLE
crio-1.21.3: kubeadmin init: unexpected fault address 0x0 during image pull

### ISSUE THREAD

**Issue by priyamalart** [cri-o/cri-o#6769]
### What happened?

When bringing up K8S cluster using crio, segfault is seen in crio. This repeats and unable to create cluster with crio.
======================
[labadmin@master ~]$ crio version
INFO[2023-03-29 10:05:46.864170709+05:30] Starting CRI-O, version: 1.21.3, git: ff0b7feb8e12509076b4b0e338b6334ce466b293(clean)
Version:       1.21.3
GitCommit:     ff0b7feb8e12509076b4b0e338b6334ce466b293
GitTreeState:  clean
BuildDate:     2023-03-06T13:32:13Z
GoVersion:     go1.18.9
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
=================================
Mar 29 09:43:03 master sudo[21606]: labadmin : TTY=pts/1 ; PWD=/home/labadmin ; USER=root ; COMMAND=/bin/kubeadm init --config /home/labadmin/config.yaml
Mar 29 09:43:03 master sudo[21606]: pam_unix(sudo:session): session opened for user root by labadmin(uid=0)
Mar 29 09:43:03 master crio[23735]: time="2023-03-29 09:43:03.586189403+05:30" level=info msg="Checking image status: k8s.gcr.io/kube-apiserver:v1.21.1" id=ac911fe0-03c2-4342-b952-f5554b9d3725 name=/runtime.v1.ImageService/ImageStatus
Mar 29 09:43:03 master crio[23735]: time="2023-03-29 09:43:03.586553419+05:30" level=info msg="Image k8s.gcr.io/kube-apiserver:v1.21.1 not found" id=ac911fe0-03c2-4342-b952-f5554b9d3725 name=/runtime.v1.ImageService/ImageStatus
Mar 29 09:43:03 master crio[23735]: time="2023-03-29 09:43:03.604925507+05:30" level=info msg="Pulling image: k8s.gcr.io/kube-apiserver:v1.21.1" id=435092bb-c260-4e7e-839b-dbcab4ca8d46 name=/runtime.v1.ImageService/PullImage
Mar 29 09:43:03 master crio[23735]: time="2023-03-29 09:43:03.610538731+05:30" level=info msg="Trying to access \"k8s.gcr.io/kube-apiserver:v1.21.1\""
Mar 29 09:43:04 master crio[23735]: time="2023-03-29 09:43:04.554779245+05:30" level=info msg="Trying to access \"k8s.gcr.io/kube-apiserver:v1.21.1\""
Mar 29 09:43:13 master crio[23735]: unexpected fault address 0x0
Mar 29 09:43:13 master crio[23735]: fatal error: fault
Mar 29 09:43:13 master crio[23735]: [signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x564459c32dff]
Mar 29 09:43:13 master crio[23735]: goroutine 94 [running]:
Mar 29 09:43:13 master crio[23735]: runtime.throw({0x56445b03fa0f?, 0xc00041e5a0?})
Mar 29 09:43:13 master crio[23735]: /usr/lib/golang/src/runtime/panic.go:992 +0x71 fp=0xc0009f9488 sp=0xc0009f9458 pc=0x564459c01c71
Mar 29 09:43:13 master crio[23735]: runtime.sigpanic()

### What did you expect to happen?

kubeadmin init must be successful. crictl must be able to pull all images.

### How can we reproduce it (as minimally and precisely as possible)?

k8s=1.21
crio=1.21.3

### CRI-O and Kubernetes version

crio --version
crio version 1.21.3
Version:       1.21.3
GitCommit:     ff0b7feb8e12509076b4b0e338b6334ce466b293
GitTreeState:  clean
BuildDate:     2023-03-06T13:32:13Z
GoVersion:     go1.18.9
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic

 kubectl version
W0329 10:08:55.569470   22139 loader.go:221] Config not found: /home/labadmin/.kube/config
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux master 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


</details>


### Additional environment details (AWS, VirtualBox, physical, etc.)

Openstack based VM

**Comment by priyamalart** [comment]
[crio.log](https://github.com/cri-o/cri-o/files/11096630/crio.log)

**Comment by haircommander** [comment]
@hasan4791 do you have the bandwidth to look into this?

**Comment by priyamalart** [comment]
To unblock the k8s installation, I switched to 1.21.7 .
Due to product limitation, we are still using K8S 1.21. Is it fine to use crio-1.21.7 or wait for 1.21.3 fix?

**Comment by hasan4791** [comment]
@haircommander Do we still need to fix this one considering the latest version is stable?

**Comment by haircommander** [comment]
yeah @priyamalart if this fixed between cri-o 1.21.3 and 1.21.7, then I would consider it fixed. is that the case?

**Comment by priyamalart** [comment]
@haircommander: If K8S 1.21 can be used with any of the cri-o 1.21.Y; Then, I will continue with cri-o 1.21.7

**Comment by priyamalart** [comment]
One more question, if 1.21.7 was latest, Why was 1.21.3 changed? Was this unexpected change or an interdependency issue?

**Comment by haircommander** [comment]
I'm not sure exactly. One possibility is it's https://github.com/cri-o/cri-o/commit/ad177504468b35b67efa8f8034eb90038af88af4 and there's also https://github.com/cri-o/cri-o/commit/c641c88b25d9c2267a38a54a9c59390816264821
